name: Toffee Token Extractor

on:
  schedule:
    - cron: '*/30 * * * *' # Automatically runs every 30 minutes
  workflow_dispatch: # Allows you to manually trigger it with a click button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        run: python extract_toffee.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add toffee_data.json
          git diff-index --quiet HEAD || git commit -m "Update Toffee live stream token [skip ci]"
          git pull --rebase origin main
          git push origin main
